// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8tx2TJEllwEf3aEUvQKhlLLFINx6Vg4',
    appId: '1:33946379507:web:04e3e002431fcc7f574386',
    messagingSenderId: '33946379507',
    projectId: 'wandering-8a2fb',
    authDomain: 'wandering-8a2fb.firebaseapp.com',
    storageBucket: 'wandering-8a2fb.firebasestorage.app',
    measurementId: 'G-85YCLM49Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDykPSEMvZ0C0cz30Cpx1ZPHX6YrdW5HM',
    appId: '1:33946379507:android:31957e8a624d1cae574386',
    messagingSenderId: '33946379507',
    projectId: 'wandering-8a2fb',
    storageBucket: 'wandering-8a2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNnAzqFJkfN0ablhcaoL8W2duiiXb1458',
    appId: '1:33946379507:ios:6dc370623f579ddb574386',
    messagingSenderId: '33946379507',
    projectId: 'wandering-8a2fb',
    storageBucket: 'wandering-8a2fb.firebasestorage.app',
    androidClientId: '33946379507-d2epihm2fkbms1gvhgaqg3242ih4jl4g.apps.googleusercontent.com',
    iosClientId: '33946379507-j0q2u66adtf7cfeppg9jq78cd3jfcjss.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNnAzqFJkfN0ablhcaoL8W2duiiXb1458',
    appId: '1:33946379507:ios:6dc370623f579ddb574386',
    messagingSenderId: '33946379507',
    projectId: 'wandering-8a2fb',
    storageBucket: 'wandering-8a2fb.firebasestorage.app',
    androidClientId: '33946379507-d2epihm2fkbms1gvhgaqg3242ih4jl4g.apps.googleusercontent.com',
    iosClientId: '33946379507-j0q2u66adtf7cfeppg9jq78cd3jfcjss.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO8tx2TJEllwEf3aEUvQKhlLLFINx6Vg4',
    appId: '1:33946379507:web:f1402fff03dd7228574386',
    messagingSenderId: '33946379507',
    projectId: 'wandering-8a2fb',
    authDomain: 'wandering-8a2fb.firebaseapp.com',
    storageBucket: 'wandering-8a2fb.firebasestorage.app',
    measurementId: 'G-7GJW7NB5YF',
  );
}
